import type { Metadata } from 'next';
import '@/app/globals.css';
import Footer from '@/app/components/Footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-kr">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
