export const KIS_API_CONFIG = {
  BASE_URL: process.env.NEXT_PUBLIC_KIS_API_BASE_URL,
  TOKEN_URL: process.env.NEXT_PUBLIC_KIS_API_TOKEN_URL,
  CLIENT_ID: process.env.NEXT_PUBLIC_KIS_API_KEY,
  CLIENT_SECRET: process.env.NEXT_PUBLIC_KIS_API_SECRET,
};
