import type { Metadata } from 'next';
import '../globals.css';
import Footer from '../components/Footer/Footer.tsx';
import Header from '../components/Header/Header.tsx';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-kr">
      <body className="dx-viewport">
        <Header
          links={[
            { name: '뉴스룸', url: '/news' },
            { name: '커뮤니티', url: '/community' },
            { name: '모의투자', url: '/stock' },
          ]}
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}
